spring:
  datasource:
#    url: jdbc:mysql://192.168.1.108:3306/pigletter?serverTimezone=GMT%2B8
    url: jdbc:mariadb://localhost:3306/pigletter?serverTimezone=UTC
    username: root
    password: maojiawei1
#   driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

  resources:
    static-locations: classpath:/static/

mybatis:
  config-location: classpath:sqlMapConfig.xml


